apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ether
  name: ami-frontend
  labels:
    app: ami-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ami-frontend
  template:
    metadata:
      labels:
        app: ami-frontend
    spec:
      nodeSelector:
        role: worker
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend
          image: ghcr.io/ether-paris/ami-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ami-secrets
                  key: GROQ_API_KEY
            - name: OPENROUTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ami-secrets
                  key: OPENROUTER_API_KEY
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ami-secrets
                  key: GOOGLE_API_KEY
            - name: ELEVENLABS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ami-secrets
                  key: ELEVENLABS_API_KEY
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ami-secrets
                  key: OPENAI_API_KEY
