apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ami-data-pvc
  namespace: ether
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi